### ISSUE TITLE
Use reviewers to specify  reviewers

### ISSUE THREAD

**Issue by shivarm** [profilecity/vidur#117]
Use reviewers to specify individual reviewers or teams of reviewers for all pull requests raised for a package manager. Use `target-branch` to specify a different branch for manifest files and for pull requests. When you use this option, the settings for this package manager will no longer affect any pull requests raised for security updates.

@amandesai01 You have to chose reviewers or you can only specify your_name 

Current file
```yml
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      target-branch: "main"
      time: "23:00"
      timezone: America/Los_Angeles
    open-pull-requests-limit: 3
    labels:
      - dependencies
    reviewers:
      - "amandesai01"
      - "other_username"
    
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      target-branch: "main"
      time: "23:00"
      timezone: America/Los_Angeles
    open-pull-requests-limit: 3
    labels:
      - dependencies
    reviewers:
      - "amandesai01"
      - "other_username"
       
```

Update one

```yml
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "23:00"
      timezone: America/Los_Angeles
    open-pull-requests-limit: 3
    labels:
      - dependencies
    reviewers:
      - "amandesai01"
      - "other_username"
    
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "23:00"
      timezone: America/Los_Angeles
    open-pull-requests-limit: 3
    labels:
      - dependencies
    reviewers:
      - "amandesai01"
      - "other_username"
```
